name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    # Build your app here

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:   
    - uses: actions/checkout@main
      with:
        cf_api: https://api.cf.us10-001.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASS }}
        cf_org: 96468441trial
        cf_space: dev
        command: push -f manifest-dev.yml
